name: Unit Test(macOS)

concurrency:
  group: macos-test-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [main]
    paths:
      - '.changeset/**'
      - '.vscode/**'
      - '.github/**'
      - 'packages/toolkit/main-doc/**'
      - 'packages/toolkit/module-doc/**'
      - 'packages/builder/builder-doc/**'
      - 'website/**'

jobs:
  ut-mac:
    runs-on: ${{ matrix.os }}
    steps:
      - run: 'echo "No required"'
